version: '3.0'

expectations:
  population_size: 10000

actions:


# actions to plot deaths over time

  generate_cohort_deaths:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/cohorts
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_2_deaths.csv

  plot_deaths:
    run: r:latest analysis/2-plot-deaths.R
    needs: [generate_cohort_deaths]
    outputs:
      moderately_sensitive:
        figure: output/plots/plot_deaths.png
